<a href="https://colab.research.google.com/github/krishnanands17/DataScienceLab/blob/main/CO1PG5-Matrix_Operations_%26_Creating_a_dataframe-30_11_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Matrix Operations

#### Matrices

In [ ]:
# Create a matrix using the 'matrix()' function of the 'numpy' module.
import numpy as np
x = np.matrix('8 7 ; 3 -5')
print(type(x))
x

<class 'numpy.matrix'>


matrix([[ 8,  7],
        [ 3, -5]])

In [ ]:
# Convert a nested Python list into a matrix using the 'matrix()' function of the 'numpy' module.
x = np.matrix([[8,7],[3,-5]])
x

matrix([[ 8,  7],
        [ 3, -5]])

#### Matrix Multiplication



$$\begin{bmatrix} 8 & 7 \\ 3	& -5	\\\end{bmatrix} \begin{bmatrix} 3 \\ 2 \\\end{bmatrix}$$

To multiply two matrices, you have to use the `matmul()` function of the `numpy` module. It takes two matrices to be multiplied as inputs and returns a new matrix.

In [ ]:
# Multiplication of the above two matrices.
a = np.matrix('8 7;3 -5')
b = np.matrix('3;2')
mul = np.matmul(a,b)
mul

matrix([[38],
        [-1]])

**Note:** The number of columns in the first matrix should be the same as the number of rows in the second matrix. Otherwise, you will get `ValueError`

####  Identity Matrix

In [ ]:
# Create an identity matrix of the dimension 5 and of 'int' type.
identity_mat = np.identity(5,dtype = int)
identity_mat


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Now let's multiply a square matrix with an identity matrix of the same dimension (say 3).

In [ ]:
# Multiply a square matrix with an identity matrix of the same dimension.
a = np.matrix('1 2 3 ; 4 5 6 ; 7 8 9')
identity_mat = np.identity(3,dtype=int)
mul = np.matmul(a,identity_mat)
mul



matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
a = np.matrix('8 7;3 -5')
identity_mat = np.identity(2,dtype=int)
mul = np.matmul(a,identity_mat)
mul

matrix([[ 8,  7],
        [ 3, -5]])

####  Multiplicative Inverse of a Matrix^


Eg. let $A$ be a matrix of dimension $3$

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

Then its inverse is

$$A^{-1} = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix}$$

Both $A$ and $A^{-1}$ have the same dimension.

If you multiply the matrix $A$ with its inverse, you should get the identity matrix of dimension $3$.

$$A^{-1} A = \begin{bmatrix} 7 & - 3 & -3 \\ -1 & 1 & 0 \\ -1 & 0 & 1 \\\end{bmatrix} \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 7 \times 1 - 3 \times 1 -3 \times 1 &7 \times 3 - 3 \times 4 -3 \times 3 & 7 \times 3 - 3 \times 3 - 3 \times 4 \\ -1 \times 1 + 1 \times 1 + 0 \times 1 & -1 \times 3 + 1 \times 4 + 0 \times 3 & -1 \times 3 + 1 \times 3 + 0 \times 4 \\ -1 \times 1 + 0 \times 1 + 1 \times 1 & -1 \times 3 + 0 \times 4 + 1 \times 3 & -1 \times 3 + 0 \times 3 + 1 \times 4 \\\end{bmatrix}$$

$$\Rightarrow A^{-1}A = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \\\end{bmatrix}$$


In [ ]:
#Multiply the above matrix with its inverse.
x = np.matrix('1 3 3 ; 1 4 3 ; 1 3 4')
inv_x = np.matrix('7 -3 -3 ; -1 1 0 ; -1 0 1')
mul = np.matmul(x,inv_x)
mul


matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

#### Determinant of a Matrix^^


$$X = \begin{bmatrix} 8 & 7 \\ 3	& -5 \\\end{bmatrix}$$

 To calculate the determinant value of a square matrix, use the `linalg.det()` function of the `numpy` module.

**Syntax:** `np.linalg.det(a)`

where `a` is some square matrix.

In [ ]:
# Calculate the determinant of the matrix X.
x = np.matrix('8 7 ; 3 -5')
det = np.linalg.det(x)
det 


-60.99999999999995

Let's calculate the determinant of the matrix

$$A = \begin{bmatrix} 1 & 3 & 3 \\ 1 & 4 & 3 \\ 1 & 3 & 4 \\\end{bmatrix}$$

using Python.

In [ ]:
#Calculate the determinant of the above matrix A.
a = np.matrix('1 3 3 ; 1 4 3 ; 1 3 4')
det = np.linalg.det(a)
det 


1.0

In [ ]:
# Calculate the inverse of the above matrix A.
a = np.matrix('1 3 3 ; 1 4 3 ; 1 3 4')
inv_a = np.linalg.inv(a)
inv_a


matrix([[ 7., -3., -3.],
        [-1.,  1.,  0.],
        [-1.,  0.,  1.]])

In [ ]:
#Create a dictionary to store weatherdata and convert it to a dtaframe
import pandas as pd
weather = {
            'Day':['1/10/21','2/10/21','3/10/21','4/10/21','5/10/21','6/10/21'],
            'City':['ERNAKULAM','KANNUR','WAYANAD','MALAPURAM','IDUKKI','TRIVANDRUM'],
            'Temp':[31,34,33,35,36,38],
            'windSpeed':[44,43,45,42,47,41]
}

# Display the first five rows of dataframe
df = pd.DataFrame(weather)
df.head()


Day       City  Temp  windSpeed
0  1/10/21  ERNAKULAM    31         44
1  2/10/21     KANNUR    34         43
2  3/10/21    WAYANAD    33         45
3  4/10/21  MALAPURAM    35         42
4  5/10/21     IDUKKI    36         47

In [ ]:
#Display the last five rows of dataframe
df = pd.DataFrame(weather)
df.tail()

Day        City  Temp  windSpeed
1  2/10/21      KANNUR    34         43
2  3/10/21     WAYANAD    33         45
3  4/10/21   MALAPURAM    35         42
4  5/10/21      IDUKKI    36         47
5  6/10/21  TRIVANDRUM    38         41